# Generated by Django 5.0 on 2025-01-27 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico.'}, max_length=254, unique=True, verbose_name='correo electrónico')),
                ('email_alternativo', models.EmailField(blank=True, help_text='Email alternativo para recuperación de cuenta', max_length=254, null=True, verbose_name='correo electrónico alternativo')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=False, help_text='Indica si este usuario debe ser tratado como activo.', verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario puede acceder al sitio de administración.', verbose_name='staff')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('email_verificado', models.BooleanField(default=False, help_text='Indica si el usuario ha verificado su dirección de email.', verbose_name='email verificado')),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True, verbose_name='código de verificación')),
                ('codigo_verificacion_expira', models.DateTimeField(blank=True, null=True, verbose_name='expiración del código de verificación')),
                ('codigo_recuperacion', models.CharField(blank=True, max_length=6, null=True, verbose_name='código de recuperación')),
                ('codigo_recuperacion_expira', models.DateTimeField(blank=True, null=True, verbose_name='expiración del código de recuperación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
