# Generated by Django 5.0 on 2025-01-27 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato: +56912345678', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número debe estar en formato: '+999999999'. Mínimo 9 y máximo 15 dígitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
