# Generated by Django 5.0 on 2025-01-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_email_verificado_usuario_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
