# Generated by Django 5.0 on 2025-01-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_foto_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='expiracion_recuperacion',
            new_name='fecha_codigo_recuperacion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
