# Generated by Django 5.0 on 2025-01-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rename_expiracion_recuperacion_usuario_fecha_codigo_recuperacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
