# Generated by Django 5.0 on 2025-01-29 13:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0003_viaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ['nombre'], 'verbose_name': 'Línea', 'verbose_name_plural': 'Líneas'},
        ),
        migrations.RemoveField(
            model_name='linea',
            name='activa',
        ),
        migrations.AddField(
            model_name='linea',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], db_index=True, default='activa', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='pasajes.bus', verbose_name='bus'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium')], default='normal', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacidad',
            field=models.PositiveIntegerField(verbose_name='capacidad'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='pasajes.linea', verbose_name='línea'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='pasajes.region', verbose_name='región'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_destino', to='pasajes.ciudad', verbose_name='destino'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='duracion',
            field=models.DurationField(help_text='Duración estimada del viaje', verbose_name='duración'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre_empresa',
            field=models.CharField(db_index=True, max_length=100, verbose_name='nombre empresa'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_origen', to='pasajes.ciudad', verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio base'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo',
            field=models.CharField(max_length=2, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='region',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='pasajes.pais', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pasajes.asiento', verbose_name='asiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_viaje',
            field=models.DateField(verbose_name='fecha de viaje'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de orden de PayPal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='pasajes.bus', verbose_name='bus'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_ruta', 'En Ruta'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_index=True, default='programado', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_salida',
            field=models.DateTimeField(verbose_name='fecha de salida'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio'),
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['bus', 'numero'], name='pasajes_asi_bus_id_3e1f44_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['linea', 'numero'], name='pasajes_bus_linea_i_5043dc_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudad',
            index=models.Index(fields=['nombre'], name='pasajes_ciu_nombre_ac5d22_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudad',
            index=models.Index(fields=['region', 'nombre'], name='pasajes_ciu_region__e1582d_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['nombre'], name='pasajes_lin_nombre_c47217_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['estado'], name='pasajes_lin_estado_3db565_idx'),
        ),
        migrations.AddIndex(
            model_name='linea',
            index=models.Index(fields=['origen', 'destino'], name='pasajes_lin_origen__4b3d73_idx'),
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['nombre'], name='pasajes_pai_nombre_055b30_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['nombre'], name='pasajes_reg_nombre_87792b_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['pais', 'nombre'], name='pasajes_reg_pais_id_0c0542_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_reserva'], name='pasajes_res_fecha_r_0dfd20_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='pasajes_res_estado_d385f1_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['fecha_salida'], name='pasajes_via_fecha_s_c5db13_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['estado'], name='pasajes_via_estado_37ed76_idx'),
        ),
    ]
