# Generated by Django 5.0 on 2025-01-29 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0004_alter_linea_options_remove_linea_activa_linea_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ['nombre_empresa', 'nombre'], 'verbose_name': 'Línea', 'verbose_name_plural': 'Líneas'},
        ),
        migrations.RemoveIndex(
            model_name='asiento',
            name='pasajes_asi_bus_id_3e1f44_idx',
        ),
        migrations.RemoveIndex(
            model_name='bus',
            name='pasajes_bus_linea_i_5043dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='ciudad',
            name='pasajes_ciu_nombre_ac5d22_idx',
        ),
        migrations.RemoveIndex(
            model_name='ciudad',
            name='pasajes_ciu_region__e1582d_idx',
        ),
        migrations.RemoveIndex(
            model_name='linea',
            name='pasajes_lin_nombre_c47217_idx',
        ),
        migrations.RemoveIndex(
            model_name='linea',
            name='pasajes_lin_estado_3db565_idx',
        ),
        migrations.RemoveIndex(
            model_name='linea',
            name='pasajes_lin_origen__4b3d73_idx',
        ),
        migrations.RemoveIndex(
            model_name='pais',
            name='pasajes_pai_nombre_055b30_idx',
        ),
        migrations.RemoveIndex(
            model_name='region',
            name='pasajes_reg_nombre_87792b_idx',
        ),
        migrations.RemoveIndex(
            model_name='region',
            name='pasajes_reg_pais_id_0c0542_idx',
        ),
        migrations.RemoveIndex(
            model_name='reserva',
            name='pasajes_res_fecha_r_0dfd20_idx',
        ),
        migrations.RemoveIndex(
            model_name='reserva',
            name='pasajes_res_estado_d385f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='viaje',
            name='pasajes_via_fecha_s_c5db13_idx',
        ),
        migrations.RemoveIndex(
            model_name='viaje',
            name='pasajes_via_estado_37ed76_idx',
        ),
        migrations.RemoveField(
            model_name='linea',
            name='estado',
        ),
        migrations.AddField(
            model_name='linea',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.bus'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.linea'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.region'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_destino', to='pasajes.ciudad'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='duracion',
            field=models.DurationField(help_text='Duración estimada del viaje'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre_empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='linea',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_origen', to='pasajes.ciudad'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.pais'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.asiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_viaje',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.bus'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_ruta', 'En Ruta'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_salida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
